export const FETCH_PLANETS_LIST_FROM_API = '[PLANETS] FETCH PLANETS LIST FROM API ACTION';
export const FETCH_PLANETS_LIST_FROM_API_SUCCESS = '[PLANETS] FETCH PLANETS LIST FROM API ACTION SUCCESS';
export const FETCH_PLANETS_LIST_FROM_API_ERROR = '[PLANETS] FETCH PLANETS LIST FROM API ACTION ERROR';
export const FETCH_PLANET_BY_ID_FROM_API = '[PLANETS] FETCH PLANETS BY ID FROM API';
export const FETCH_PLANET_BY_ID_FROM_API_SUCCESS = '[PLANETS] FETCH PLANETS BY ID FROM API SUCCESS';
export const FETCH_PLANET_BY_ID_FROM_API_ERROR = '[PLANETS] FETCH PLANETS BY ID FROM API ERROR';
export const FETCH_PLANET_SCHEME_FROM_API = '[PLANETS] FETCH PLANETS SCHEME FROM API';
export const FETCH_PLANET_SCHEME_FROM_API_SUCCESS = '[PLANETS] FETCH PLANETS SCHEME FROM API SUCCESS';
export const FETCH_PLANET_SCHEME_FROM_API_ERROR = '[PLANETS] FETCH PLANETS SCHEME FROM API ERROR';

export const HOST = 'https://swapi.co';
export const PLANET_URL = {
    LIST: '/api/planets/',
    BY_ID: (id: number | null) => `/api/planets/${id}`,
    SCHEMA: '/api/planets/schema/ '
};