/* tslint:disable:object-literal-sort-keys */
export const PLANET_ACTIONS = {
    FETCH_ALL_PLANETS_ACTION: "Fetch all planets from api",
    FETCH_ALL_PLANETS_ERROR_ACTION: "Fetch  all planets from api error",
    FETCH_ALL_PLANETS_SUCCESS_ACTION: "Fetch  all planets from api success",
};

export const FILM_ACTIONS = {
    FETCH_FILMS_LIST_FROM_API: "[FILM LIST] Fetch films list from api",
    FETCH_FILMS_FROM_API_ERROR: "[FILM LIST] Fetch films list from api ERROR",
    FETCH_FILMS_FROM_API_SUCCESS: "[FILM LIST] Fetch films list from api SUCCESS",
    FETCH_FILM_SCHEME_ACTION: "[FILM SCHEME] GET FILM SCHEME FROM API",
    FETCH_FILM_SCHEME_SUCCESS_ACTION: "[FILM SCHEME] GET FILM SCHEME FROM API SUCCESS",
    FETCH_FILM_SCHEME_ERROR_ACTION: "[FILM SCHEME] GET FILM SCHEME FROM API ERROR ",
    FETCH_FILM_BY_ID_ACTION: "[FILM BY ID] GET FILM BY ID FROM API",
    FETCH_FILM_BY_ID_SUCCESS_ACTION: "[FILM BY ID]  GET FILM BY ID FROM API SUCCESS ",
    FETCH_FILM_BY_ID_ERROR_ACTION: "[FILM BY ID]  GET FILM BY ID FROM API ERROR",
};
